-- Migration V4: Seed Granular Menu Roles
INSERT INTO roles (name) VALUES ('ROLE_SLOTS') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_PRICING') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_BOOKINGS') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ANALYTICS') ON CONFLICT DO NOTHING;
