-- Seed functional and administrative roles for staff management
INSERT INTO roles (name) VALUES ('ROLE_ADMIN') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_STAFF') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_GATEKEEPER') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_SLOTS') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_PRICING') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_BOOKINGS') ON CONFLICT DO NOTHING;
INSERT INTO roles (name) VALUES ('ROLE_ANALYTICS') ON CONFLICT DO NOTHING;
